config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ride_tracks#home'

  namespace :ride_tracks do
    get :home
    get :price_estimate
  end

  namespace :currencies do
    get :home
    get :convert
    get :history
    get :currencies_list
  end
end

app/models/concerns/constants/currency.rb
module Constants
  module Currency
    DEFAULT_TO   = 'GB'
    DEFAULT_FROM = 'US'

    DEFAULT_FROM_AND_TO = [DEFAULT_FROM, DEFAULT_TO]
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  layout 'currencies/application'

  def home
    @exchange_rate = currency_service.get_exchange_rate_from_ip('71.232.211.223')
    @currencies    = currency_service.get_currencies
    @histories     = currency_service.get_currency_histories(
      from: @exchange_rate.from_currency.code,
      to:   @exchange_rate.to_currency.code
    )
  end

  def convert
    @currencies    = currency_service.get_currencies
    @exchange_rate = currency_service.get_exchange_rate(from: params[:from], to: params[:to])
    @histories     = currency_service.get_currency_histories(from: params[:from], to: params[:to])
  end

  def history
    @histories = currency_service.get_currency_histories(from: params[:from], to: params[:to])
    @histories_data = {
      rates: @histories.map(&:rate),
      dates: @histories.map(&:date),
      label: "#{params[:from]} to #{params[:to]}"
    }
  end
  
  def currencies_list
    @currencies = currency_service.get_currencies
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
  def currency_select_option(currency:, selected:)
    content_tag :option,
                currency_name_with_code(currency: currency),
                currency_name: formatted_currency_name(currency_name: currency.name),
                value: currency.code,
                selected: selected,
                data: {icon: "currency-flag currency-flag-#{(currency.code).try(:downcase)}"}
  end

  def formatted_currency_name(currency_name:)
    currency_name.split.map(&:capitalize).join(' ')
  end

  def currency_name_with_code(currency:)
    "#{formatted_currency_name(currency_name: currency.name)} (#{currency.code})"
  end
end

app/views/layouts/currencies/_footer.html.haml
%footer.py-5.bg-black
  .container
    %p.m-0.text-center.text-white.small Copyright © Your Website 2018
  / /.container

app/views/layouts/currencies/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.navbar-custom.fixed-top
  .container
    = link_to fontawesome_icon('fas fa-coins', 'Currency Converter'), currencies_home_path, class: 'navbar-brand'
    %button.navbar-toggler{'aria-controls': 'navbarResponsive', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation', 'data-target': '#navbarResponsive', 'data-toggle': 'collapse', type: 'button'}
      %span.navbar-toggler-icon

app/views/layouts/currencies/application.html.haml
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %title Currency Convert


    %link{crossorigin: 'anonymous', href: 'https://use.fontawesome.com/releases/v5.2.0/css/all.css', integrity: 'sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ', rel: 'stylesheet'}
    %script{crossorigin: "anonymous", integrity: "sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=", src: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"}
    %script{:src => "http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"}
    %link{crossorigin: 'anonymous', href: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', integrity: 'sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO', rel: 'stylesheet'}
    %script{crossorigin: 'anonymous', integrity: 'sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy', src: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'}
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore.js', type: 'text/javascript'}

    %link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/css/flag-icon.min.css", :integrity => "sha256-D+ZpDJjhGxa5ffyQkuTvwii4AntFGBZa4jUhSpdlhjM=", :rel => "stylesheet"}/

    -#Bootstrap Select
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css", :rel => "stylesheet"}/
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"}


    %script{:crossorigin => "anonymous", :integrity => "sha256-o8aByMEvaNTcBsw94EfRLbBrJBI+c3mjna/j4LrfyJ8=", :src => "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"}

    %link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/currency-flags/1.8.0/currency-flags.css", :integrity => "sha256-1nLh1SuCTXvjlsdqnaw4bmW0ybmaHRzWMFuEg7iaRRM=", :rel => "stylesheet"}



    = stylesheet_link_tag    'currencies/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'currencies/application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/currencies/header'
    = yield
    = render partial: 'layouts/currencies/footer'