config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ride_tracks#home'

  namespace :ride_tracks do
    get :home
    get :price_estimate
  end

  namespace :currencies do
    get :home
    get :convert
    get :history
    get :currencies_list
  end
end

app/controllers/ride_tracks_controller.rb
class RideTracksController < ApplicationController

  layout 'ride_tracks/application'

  def home
  end

  def price_estimate
    @price_estimates = ride_track_service.get_price_estimates(request: build_request)
  rescue Exceptions::RideTrack::InvalidParameters => e
    @error = e.message
  end

  private

  def estimate_origin_params
    params.require(:origin_details).permit ESTIMATE_PARAMS_LIST
  end

  def estimate_destination_params
    params.require(:destination_details).permit ESTIMATE_PARAMS_LIST
  end

  ESTIMATE_PARAMS_LIST = [:latitude, :longitude, :city, :state, :postal_code, :country]

  def build_request
    Domains::RideTrack::PriceEstimateRequest.new(
        origin_details: estimate_origin_params,
        destination_details: estimate_destination_params
    )
  end
end

app/views/ride_tracks/_coordinate_details.html.erb
<%= hidden_field_tag 'origin_details[latitude]', nil, {id: 'origin-latitude'}  %>
<%= hidden_field_tag 'origin_details[longitude]', nil, {id: 'origin-longitude'}  %>

<%= hidden_field_tag 'destination_details[latitude]', nil, {id: 'destination-latitude'} %>
<%= hidden_field_tag 'destination_details[longitude]', nil, {id: 'destination-longitude'} %>

app/views/ride_tracks/_coordinates_search.html.erb
<%= form_tag(ride_tracks_price_estimate_path, method: :get, remote: true, id: 'coordinate-search') do %>
  <div class="form-group">
    <%= label_tag I18n.t('ride_track.labels.origin') %>
    <%= text_field_tag 'origin_details[address]', nil,
                       class: 'form-control',
                       id: 'origin-address',
                       placeholder: 'Central Park, Manhattan, New York, NY, USA',
                       required: true %>
  </div>
  <div class="form-group">
    <%= label_tag I18n.t('ride_track.labels.destination') %>
    <%= text_field_tag 'destination_details[address]', nil,
                       class: 'form-control',
                       id: 'destination-address',
                       placeholder: 'Times Square, Manhattan, New York, NY, USA',
                       required: true %>
  </div>

  <%= render partial: 'coordinate_details' %>

  <%= submit_tag I18n.t('ride_track.buttons.estimate'), class: 'btn btn-primary', id: 'estimate', name: 'estimate' %>
<% end %>

<script>
    $(document).ready(function () {
        coordinatesSearch.init();
    });
</script>

app/views/ride_tracks/_errors.html.erb
<div class="alert alert-danger text-center" role="alert">
  <% errors.each do |e| %>
    <li><%= e.html_safe %></li>
  <% end %>
</div>

app/views/ride_tracks/_estimates.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <%= render 'ride_tracks/fare_details', fare_details: @price_estimates.fare_details %>
      <%= render 'ride_tracks/filter', filters: @price_estimates.filters %>
    </div>
  </div>

  <div class="col-md-9">
    <% @price_estimates.estimates.each_slice(4).each do |slice| %>
      <div class="ride-share-estimates pricing card-deck flex-column flex-md-row mb-3">
        <% slice.each do |pe| %>
          <%= render 'ride_tracks/provider_price_estimate', price_estimate: pe %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div id="directions" style='width: 100%; height: 400px;'></div>
</div>

<script>
    mapService.directions('<%= @price_estimates.request.origin.latitude %>',
        '<%= @price_estimates.request.origin.longitude %>',
        '<%= @price_estimates.request.destination.latitude %>',
        '<%= @price_estimates.request.destination.longitude %>',
        '#directions'
    );
</script>

app/views/ride_tracks/_fare_details.html.erb
<div class="card-group-item">
  <div class="card-header text-center">
    <h4>Fare Details</h4>
  </div>

  <div class="card-body ">
    <h5><i class="fas fa-arrows-alt-h text-muted fixed-width-1"></i> Distance</h5>
    <%= distance_with_units(distance: fare_details.minimum_distance, unit: fare_details.distance_unit) %>

    <hr>

    <h5><i class="fas fa-hourglass-half text-muted fixed-width-1"></i> Duration</h5>
    <%= minimum_distance(duration: fare_details.minimum_duration_in_minutes) %>
  </div>
</div>

app/views/ride_tracks/_filter.html.erb
<div class="filters">

  <% if filters.providers.any? %>
    <div class="card-group-item">
      <div class="card-header text-center">
        <h4>Providers</h4>
      </div>

      <div class="card-body">
        <% filters.providers.each do |provider, count| %>
          <div class="custom-control custom-checkbox">
            <span class="float-right badge badge-light round"><%= count %></span>
            <input type="checkbox" class="custom-control-input" id="<%= provider %>">
            <label class="custom-control-label" for="<%= provider %>"><%= provider.classify %></label>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>


  <% if filters.capacities.any? %>
    <div class="card-group-item">
      <div class="card-header text-center">
        <h4>Capacities</h4>
      </div>

      <div class="card-body">
        <% filters.capacities.each do |capacity, count| %>
          <div class="custom-control custom-checkbox">
            <span class="float-right badge badge-light round"><%= count %></span>
            <input type="checkbox" class="custom-control-input" id="<%= capacity %>">
            <label class="custom-control-label" for="<%= capacity %>"><%= "#{capacity} People" %></label>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>

  <% if filters.features.any? %>
    <div class="card-group-item">
      <div class="card-header text-center">
        <h4>Features</h4>
      </div>

      <div class="card-body">
        <% filters.features.each do |feature, count| %>
          <div class="custom-control custom-checkbox">
            <span class="float-right badge badge-light round"><%= count %></span>
            <input type="checkbox" class="custom-control-input" id="<%= feature %>">
            <label class="custom-control-label" for="<%= feature %>"><%= feature.titleize %></label>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>

</div>

app/views/ride_tracks/_information.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-4 service service1">
      <i class="m-3 fas fa-directions fa-2x"></i>
      <h4>Directions</h4>
      <p>Get directions from your place of origin to destination.</p>
    </div>

    <div class="col-md-4 service service2">
      <i class="m-3 fas fa-clock fa-2x"></i>
      <h4>Time Estimates</h4>
      <p>Get real time time estimates based on ride and traffic availability.</p>
    </div>

    <div class="col-md-4 service service3">
      <i class="m-3 fas fa-dollar-sign fa-2x"></i>
      <h4>Price Estimates</h4>
      <p>Get real time price estimates along with the on-demand pricing.</p>
    </div>
  </div>
</div>

app/views/ride_tracks/_provider_price_estimate.html.erb
<div class="ride-share-estimate card ride-share provider px-3 mb-4 col-md-3" data-category="<%= categories(product: price_estimate.product) %>">
  <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom text-white text-center <%= price_estimate.provider %>">
    <%= price_estimate.display_name %>
  </span>
  <div class="bg-transparent card-header text-center border-0 <%= price_estimate.provider %>">
    <%= cost_with_currency(cost: price_estimate.average_estimate, currency: price_estimate.currency_code) %>
  </div>
  <br>
  <table class="card-pricing table table-striped table-sm small">
    <tbody>
    <% if price_estimate&.product&.has_price_details? %>
      <tr>
        <th class="text-left"><%= I18n.t('ride_track.labels.capacity') %></th>
        <td class="text-right"><%= price_estimate.product.capacity %> </td>
      </tr>
      <tr>
        <th class="text-left"><%= I18n.t('ride_track.labels.cancellation') %></th>
        <td class="text-right"><%= price_estimate.product.cancellation_fee %></td>
      </tr>
      <tr>
        <th class="text-left"><%= I18n.t('ride_track.labels.cost_per_minute') %></th>
        <td class="text-right"><%= price_estimate.product.cost_per_minute %></td>
      </tr>
      <tr>
        <th class="text-left"><%= I18n.t('ride_track.labels.cost_per_distance', distance_unit: price_estimate.product.distance_unit.classify) %></th>
        <td class="text-right"><%= price_estimate.product.cost_per_distance %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <input type="button" value="<%= I18n.t('ride_track.buttons.ride_now') %>" class="<%= price_estimate.provider %> btn text-white mb-2">
  </div>
</div>

app/views/ride_tracks/home.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="container text-center ">
      <h1><i class="fas fa-taxi"></i> Fare Estimate Online</h1>
      <h3>Instantly Calculate the Cost of a Ride!</h3>

      <hr>

      <div id="coordinates_search" class="container w-50">
        <%= render partial: 'coordinates_search' %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div id="price_estimates">
    <!--  Place Holder-->
  </div>
</div>

<%= render 'information' %>

app/views/ride_tracks/price_estimate.js.erb
var estimateContainer = $('#price_estimates')

<% errors = @price_estimates.try(:errors) || [@error] %>

<% if errors.try(:any?) %>
  estimateContainer.empty().html("<%=j render 'ride_tracks/errors', errors: errors %>");
<% elsif @price_estimates.try(:estimates).try(:any?) %>
  estimateContainer.empty().html("<%=j render 'ride_tracks/estimates' %>");
<% end %>